require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.1'

def sharedPods
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  pod 'react-native-config', :path => '../node_modules/react-native-config'

 
end

target 'GoldWallet' do
  sharedPods
end

target 'GoldWallet Beta' do
  sharedPods
end

target 'GoldWallet Stage' do
  sharedPods
end

target 'GoldWallet Dev' do
  sharedPods  

  post_install do |installer|
    react_native_post_install(installer)
  end
end
