import { readFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const packageJson = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
const checkLightScript = packageJson.scripts['android:dev:check-light'] || '';

const requiredCheckLightScripts = [
  'check:node-runtime-version',
  'android:dev:check-warning-guard',
  'android:dev:check-artifact-guard',
  'check:android-dev-env-audit-guard',
  'check:metro-dev-runtime-audit-guard',
  'check:rn-upgrade-path-audit-guard',
  'rn:upgrade-path:audit',
  'check:react-renderer-version-guard',
  'react:renderer-version:audit',
  'check:camera-usage-guard',
  'check:camera-usage-scope',
  'check:qr-scan-caller-guard',
  'check:qr-scan-callers',
  'check:qr-scanner-validation-scripts',
  'check:qr-render-usage-guard',
  'check:qr-render-usage',
  'check:qr-render-validation-scripts',
  'check:legacy-android-autolink-guard',
  'check:legacy-android-autolink',
  'check:sentry-usage-guard',
  'check:sentry-usage-scope',
  'check:sentry-release-integration-guard',
  'check:sentry-release-integration',
  'check:codepush-usage-guard',
  'check:codepush-usage-scope',
  'check:firebase-usage-guard',
  'check:firebase-usage-scope',
  'check:push-notification-ios-usage-guard',
  'check:push-notification-ios-usage-scope',
  'check:release-service-env-keys-guard',
  'check:release-service-env-keys',
  'check:android-env-config-files-guard',
  'check:android-env-config-files',
  'check:ios-scheme-config-guard',
  'check:ios-scheme-config',
  'check:explorer-env-config-readiness-guard',
  'check:explorer-env-config-readiness',
  'check:store-metadata-readiness-guard',
  'check:store-metadata-readiness',
  'check:rebranding-release-config-readiness-guard',
  'check:rebranding-release-config-readiness',
  'check:storage-network-usage-guard',
  'check:storage-network-usage',
  'check:storage-network-validation-scripts-guard',
  'check:storage-network-validation-scripts',
  'check:wallet-crypto-validation-scripts',
  'check:transaction-details-amount-labels',
  'check:native-module-inventory-guard',
  'check:native-module-inventory',
  'check:native-module-upgrade-plan-guard',
  'check:native-module-upgrade-plan',
  'check:flipper-removal',
  'check:git-deps-snapshot-summary-guard',
  'check:wallet-crypto-latest-snapshot-summary-guard',
  'check:direct-outdated-snapshot-summary-guard',
  'check:node-fetch-resolution-summary-guard',
  'check:secure-storage-removal-readiness-summary-guard',
  'check:rn-nodeify-shim-guard',
  'check:rn-nodeify-shims',
  'check:modernization-log-id-guard',
  'check:modernization-log-ids',
  'typescript:check',
  'check:diff-whitespace',
];

const docs = [
  {
    path: 'README.md',
    terms: [
      'android:dev:env-audit',
      'metro:dev-runtime:audit',
      'rn:upgrade-path:audit',
      'check:rn-upgrade-path-audit-guard',
      'android:dev:check-light',
      'Android dev environment audit',
      'Metro dev runtime audit',
      'Java/SDK/ADB toolchain',
      'QR scanner validation scripts',
      'QR render validation scripts',
      'CodePush usage',
      'Firebase usage',
      'iOS push notification bridge',
      'legacy Android autolink disables',
      'Sentry release integration',
      'release-service env keys',
      'Android env mapping',
      'iOS scheme config mapping',
      'explorer/env readiness',
      'store metadata readiness',
      'rebranding release-config readiness',
      'storage/network usage',
      'storage/network validation scripts',
      'wallet crypto validation scripts',
      'transaction details amount label guard',
      'native module inventory and upgrade-plan',
      'git dependency snapshot guard',
      'wallet crypto latest snapshot guard',
      'direct outdated snapshot guard',
      'React Native renderer exact-version guard',
      'node-fetch resolution guard',
      'secure-storage removal readiness guard',
      'modernization log ID guard',
      'modernization log ID guard self-check',
      'check:node-runtime-version',
    ],
  },
  {
    path: 'docs/android-modernization-workflow.md',
    terms: [
      'android:dev:env-audit',
      'active Node version',
      'environment audit checks',
      'check:metro-dev-runtime-audit-guard',
      'rn:upgrade-path:audit',
      'check:rn-upgrade-path-audit-guard',
      'CodePush usage guard self-check',
      'Firebase usage guard self-check',
      'iOS push notification usage guard self-check',
      'check:codepush-usage-scope',
      'check:firebase-usage-scope',
      'check:push-notification-ios-usage-scope',
      'check:qr-scanner-validation-scripts',
      'check:qr-render-validation-scripts',
      'legacy Android autolink guard self-check',
      'check:legacy-android-autolink',
      'Sentry release integration guard self-check',
      'check:sentry-release-integration',
      'check:release-service-env-keys',
      'Android envConfigFiles guard self-check',
      'check:android-env-config-files',
      'iOS scheme config guard self-check',
      'check:ios-scheme-config',
      'explorer/env readiness guard self-check',
      'check:explorer-env-config-readiness',
      'store metadata readiness guard self-check',
      'check:store-metadata-readiness',
      'rebranding release-config readiness guard self-check',
      'check:rebranding-release-config-readiness',
      'storage/network usage guard self-check',
      'check:storage-network-usage',
      'storage/network validation script guard self-check',
      'check:storage-network-validation-scripts',
      'check:wallet-crypto-validation-scripts',
      'transaction details amount label guard',
      'git dependency snapshot guard self-check',
      'wallet crypto latest snapshot guard self-check',
      'direct outdated snapshot guard self-check',
      'React Native renderer exact-version guard self-check',
      'node-fetch resolution guard self-check',
      'secure-storage removal readiness guard self-check',
      'devRelease`, `stageRelease`, `prodRelease`, and `betaRelease',
      'ANDROID_RELEASE_VARIANTS=dev,stage,prod,beta',
      'feature/bem-37-590-android-release-evidence-refresh',
      'release-input fingerprint',
      'iOS macOS validation prerequisite summaries as one aggregate gate',
      'check:modernization-log-id-guard',
      'check:modernization-log-ids',
      'check:node-runtime-version',
    ],
  },
  {
    path: 'docs/wallet-modernization-baseline.md',
    terms: [
      'android:dev:env-audit',
      'metro:dev-runtime:audit',
      'rn:upgrade-path:audit',
      'check:rn-upgrade-path-audit-guard',
      'Android dev environment audit',
      'Metro dev runtime audit',
      'CodePush usage self-check/inventory guard',
      'Firebase usage self-check/inventory guard',
      'iOS push notification usage self-check/inventory guard',
      'QR scanner validation script guard',
      'QR render validation script guard',
      'legacy Android autolink self-check/guard',
      'Sentry release integration self-check/guard',
      'release-service env key self-check/guard',
      'Android env mapping self-check/guard',
      'iOS scheme config self-check/guard',
      'explorer/env readiness self-check/guard',
      'store metadata readiness self-check/guard',
      'rebranding release-config readiness self-check/guard',
      'storage/network usage self-check/guard',
      'storage/network validation script self-check/guard',
      'wallet crypto validation script guard',
      'transaction details amount label guard',
      'git dependency snapshot guard',
      'wallet crypto latest snapshot guard',
      'direct outdated snapshot guard',
      'React Native renderer exact-version guard',
      'node-fetch resolution guard',
      'secure-storage removal readiness guard',
      'iOS release readiness and iOS macOS validation prerequisites with generated summary validation',
      'Android lightweight check runs',
      'modernization log ID guard',
      'modernization log ID guard self-check',
      'check:node-runtime-version',
    ],
  },
];

const errors = [];

requiredCheckLightScripts.forEach(scriptName => {
  if (!checkLightScript.includes(scriptName)) {
    errors.push(`android:dev:check-light is missing ${scriptName}`);
  }
});

docs.forEach(doc => {
  const content = readFileSync(path.join(root, doc.path), 'utf8');

  doc.terms.forEach(term => {
    if (!content.includes(term)) {
      errors.push(`${doc.path} is missing "${term}"`);
    }
  });
});

if (errors.length > 0) {
  console.error('Android lightweight check documentation is stale:');
  errors.forEach(error => console.error(`- ${error}`));
  process.exit(1);
}

console.log('Android lightweight check documentation matches the guarded check groups.');
